// ISO 639-1 language codes supported by Whisper
export const LANGUAGES = [
  { code: 'auto', name: 'اكتشاف تلقائي (اللغة الأصلية)' },
  { code: 'auto-translate', name: 'اكتشاف تلقائي (الترجمة إلى الإنجليزية)' },
  { code: 'en', name: 'الإنجليزية' },
  { code: 'zh', name: 'الصينية' },
  { code: 'de', name: 'الألمانية' },
  { code: 'es', name: 'الإسبانية' },
  { code: 'ru', name: 'الروسية' },
  { code: 'ko', name: 'الكورية' },
  { code: 'fr', name: 'الفرنسية' },
  { code: 'ja', name: 'اليابانية' },
  { code: 'pt', name: 'البرتغالية' },
  { code: 'tr', name: 'التركية' },
  { code: 'pl', name: 'البولندية' },
  { code: 'ca', name: 'الكتالونية' },
  { code: 'nl', name: 'الهولندية' },
  { code: 'ar', name: 'العربية' },
  { code: 'sv', name: 'السويدية' },
  { code: 'it', name: 'الإيطالية' },
  { code: 'id', name: 'الإندونيسية' },
  { code: 'hi', name: 'الهندية' },
  { code: 'fi', name: 'الفنلندية' },
  { code: 'vi', name: 'الفيتنامية' },
  { code: 'he', name: 'العبرية' },
  { code: 'uk', name: 'الأوكرانية' },
  { code: 'el', name: 'اليونانية' },
  { code: 'ms', name: 'الماليزية' },
  { code: 'cs', name: 'التشيكية' },
  { code: 'ro', name: 'الرومانية' },
  { code: 'da', name: 'الدنماركية' },
  { code: 'hu', name: 'المجرية' },
  { code: 'ta', name: 'التاميلية' },
  { code: 'no', name: 'النرويجية' },
  { code: 'th', name: 'التايلاندية' },
  { code: 'ur', name: 'الأردية' },
  { code: 'hr', name: 'الكرواتية' },
  { code: 'bg', name: 'البلغارية' },
  { code: 'lt', name: 'الليتوانية' },
];
